apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "Test Generation Action"
inputs:
  token:
    description: 'AI engine token'
    required: true

runs:
  using: composite
  steps:
    - id: generate-tests
      name: generate-tests
      uses: docker://public.ecr.aws/l7o7z1g8/actions/ai_testgen_action:latest
      shell: sh
      env:
        OPENAI_API_KEY: ${{ inputs.token }}
      run: |
        python3 testgen.py
