name: publish-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  push:
    branches:
      - '**'
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build-test-generation-action:
    steps:
      - name: Get sourcecode.
        uses: cloudbees-io/checkout@v1
      - id: build
        name: Build, scan and push to test harbor
        uses: calculi-corp/cb-internal-shared-actions/build/action@v3
        with:
          registry-url: ${{ vars.STAGING_ECR_REGISTRY }}
          registry-image-name: ${{ vars.workflow_execution_env == 'production' && 'actions/test-generation-actions' || 'throwaway/actions/test-generation-actions' }}
          docker-file: Dockerfile
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          kaniko-build: "true"
          action: "ai_testgen_action"
          trufflehog-scan-container: "true"
